"""add zoho_connections table

Revision ID: 80091693e6b5
Revises: 9ba4431aa2f7
Create Date: 2026-03-11 12:39:28.804627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80091693e6b5'
down_revision: Union[str, Sequence[str], None] = '9ba4431aa2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoho_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('zoho_org_id', sa.String(length=120), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_email', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_zoho_connections_company')
    )
    op.create_index(op.f('ix_zoho_connections_company_id'), 'zoho_connections', ['company_id'], unique=False)
    op.create_index('ix_zoho_connections_tenant_company', 'zoho_connections', ['tenant_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_zoho_connections_tenant_id'), 'zoho_connections', ['tenant_id'], unique=False)
    op.drop_table('playing_with_neon')
    op.drop_constraint(op.f('weekly_metrics_weekly_report_id_key'), 'weekly_metrics', type_='unique')
    op.create_index(op.f('ix_weekly_metrics_weekly_report_id'), 'weekly_metrics', ['weekly_report_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_metrics_weekly_report_id'), table_name='weekly_metrics')
    op.create_unique_constraint(op.f('weekly_metrics_weekly_report_id_key'), 'weekly_metrics', ['weekly_report_id'], postgresql_nulls_not_distinct=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_index(op.f('ix_zoho_connections_tenant_id'), table_name='zoho_connections')
    op.drop_index('ix_zoho_connections_tenant_company', table_name='zoho_connections')
    op.drop_index(op.f('ix_zoho_connections_company_id'), table_name='zoho_connections')
    op.drop_table('zoho_connections')
    # ### end Alembic commands ###
