"""create weekly reports and metrics

Revision ID: 9ba4431aa2f7
Revises: 09da82ba64f7
Create Date: 2026-03-03 12:45:34.227832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba4431aa2f7'
down_revision: Union[str, Sequence[str], None] = '09da82ba64f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sales_inc_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sales_ex_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wages', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('holiday_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('food_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fixed_costs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('variable_costs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loans_hp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'week_ending', name='uq_weekly_reports_tenant_company_week')
    )
    op.create_index(op.f('ix_weekly_reports_company_id'), 'weekly_reports', ['company_id'], unique=False)
    op.create_index('ix_weekly_reports_tenant_company_week_desc', 'weekly_reports', ['tenant_id', 'company_id', 'week_ending'], unique=False)
    op.create_index(op.f('ix_weekly_reports_tenant_id'), 'weekly_reports', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_ending'), 'weekly_reports', ['week_ending'], unique=False)
    op.create_table('weekly_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('weekly_report_id', sa.UUID(), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_margin_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('wage_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('wage_pct_ex_holiday', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('cash_left_after_wages_food', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('projected_net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_margin_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('flag_high_wage', sa.Boolean(), nullable=False),
    sa.Column('flag_negative_profit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_report_id'], ['weekly_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'weekly_report_id', name='uq_weekly_metrics_tenant_company_report'),
    sa.UniqueConstraint('weekly_report_id')
    )
    op.create_index(op.f('ix_weekly_metrics_company_id'), 'weekly_metrics', ['company_id'], unique=False)
    op.create_index('ix_weekly_metrics_tenant_company', 'weekly_metrics', ['tenant_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_weekly_metrics_tenant_id'), 'weekly_metrics', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_metrics_tenant_id'), table_name='weekly_metrics')
    op.drop_index('ix_weekly_metrics_tenant_company', table_name='weekly_metrics')
    op.drop_index(op.f('ix_weekly_metrics_company_id'), table_name='weekly_metrics')
    op.drop_table('weekly_metrics')
    op.drop_index(op.f('ix_weekly_reports_week_ending'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_tenant_id'), table_name='weekly_reports')
    op.drop_index('ix_weekly_reports_tenant_company_week_desc', table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_company_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
