"""add financial categories and report items

Revision ID: f55161f2527f
Revises: 80091693e6b5
Create Date: 2026-03-22 14:17:29.073228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55161f2527f'
down_revision: Union[str, Sequence[str], None] = '80091693e6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_categories_tenant_id'), 'financial_categories', ['tenant_id'], unique=False)
    op.create_table('weekly_report_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('weekly_report_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['financial_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_report_id'], ['weekly_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_report_items_category_id'), 'weekly_report_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_company_id'), 'weekly_report_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_tenant_id'), 'weekly_report_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_weekly_report_items_weekly_report_id'), 'weekly_report_items', ['weekly_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_report_items_weekly_report_id'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_tenant_id'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_company_id'), table_name='weekly_report_items')
    op.drop_index(op.f('ix_weekly_report_items_category_id'), table_name='weekly_report_items')
    op.drop_table('weekly_report_items')
    op.drop_index(op.f('ix_financial_categories_tenant_id'), table_name='financial_categories')
    op.drop_table('financial_categories')
    # ### end Alembic commands ###
